/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountCreateRequest,
  AccountResponse,
  AccountWithStatusResponse,
  ErrorResponse,
  MeterReadingCreateRequest,
  MeterReadingResponse,
  PaymentCreateRequest,
  PaymentResponse,
  ServiceInfoDto,
} from '../models/index';
import {
    AccountCreateRequestFromJSON,
    AccountCreateRequestToJSON,
    AccountResponseFromJSON,
    AccountResponseToJSON,
    AccountWithStatusResponseFromJSON,
    AccountWithStatusResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    MeterReadingCreateRequestFromJSON,
    MeterReadingCreateRequestToJSON,
    MeterReadingResponseFromJSON,
    MeterReadingResponseToJSON,
    PaymentCreateRequestFromJSON,
    PaymentCreateRequestToJSON,
    PaymentResponseFromJSON,
    PaymentResponseToJSON,
    ServiceInfoDtoFromJSON,
    ServiceInfoDtoToJSON,
} from '../models/index';

export interface CreateRequest {
    accountCreateRequest: AccountCreateRequest;
}

export interface Create1Request {
    accountId: number;
    meterReadingCreateRequest: MeterReadingCreateRequest;
}

export interface Create2Request {
    accountId: number;
    paymentCreateRequest: PaymentCreateRequest;
}

export interface GetByAccountRequest {
    accountId: number;
}

export interface GetByAccount1Request {
    accountId: number;
}

export interface GetByIdRequest {
    id: number;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for create without sending the request
     */
    async createRequestOpts(requestParameters: CreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'accountCreateRequest',
                'Required parameter "accountCreateRequest" was null or undefined when calling create().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/accounts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountCreateRequestToJSON(requestParameters['accountCreateRequest']),
        };
    }

    /**
     * Создаёт новый лицевой счёт для указанной услуги. Номер счёта должен быть уникален в рамках типа услуги. Допустимые символы в номере: цифры, точка, тире.
     * Создать лицевой счёт
     */
    async createRaw(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountResponse>> {
        const requestOptions = await this.createRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountResponseFromJSON(jsonValue));
    }

    /**
     * Создаёт новый лицевой счёт для указанной услуги. Номер счёта должен быть уникален в рамках типа услуги. Допустимые символы в номере: цифры, точка, тире.
     * Создать лицевой счёт
     */
    async create(requestParameters: CreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountResponse> {
        const response = await this.createRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for create1 without sending the request
     */
    async create1RequestOpts(requestParameters: Create1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling create1().'
            );
        }

        if (requestParameters['meterReadingCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'meterReadingCreateRequest',
                'Required parameter "meterReadingCreateRequest" was null or undefined when calling create1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/accounts/{accountId}/readings`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MeterReadingCreateRequestToJSON(requestParameters['meterReadingCreateRequest']),
        };
    }

    /**
     * Регистрирует показание прибора учёта для указанного лицевого счёта.  Ограничения: • Услуга должна поддерживать счётчик (hasMeter = true) • Показание — строка из цифр строго фиксированной длины:   - Газ: ровно 4 цифры (например, \"0523\")   - Вода: ровно 4 цифры (например, \"1047\")   - Электроэнергия: ровно 5 цифр (например, \"28319\") • Для услуг без счётчика (Домофон, Отопление и др.) операция запрещена
     * Передать показание счётчика
     */
    async create1Raw(requestParameters: Create1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeterReadingResponse>> {
        const requestOptions = await this.create1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeterReadingResponseFromJSON(jsonValue));
    }

    /**
     * Регистрирует показание прибора учёта для указанного лицевого счёта.  Ограничения: • Услуга должна поддерживать счётчик (hasMeter = true) • Показание — строка из цифр строго фиксированной длины:   - Газ: ровно 4 цифры (например, \"0523\")   - Вода: ровно 4 цифры (например, \"1047\")   - Электроэнергия: ровно 5 цифр (например, \"28319\") • Для услуг без счётчика (Домофон, Отопление и др.) операция запрещена
     * Передать показание счётчика
     */
    async create1(requestParameters: Create1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeterReadingResponse> {
        const response = await this.create1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for create2 without sending the request
     */
    async create2RequestOpts(requestParameters: Create2Request): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling create2().'
            );
        }

        if (requestParameters['paymentCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'paymentCreateRequest',
                'Required parameter "paymentCreateRequest" was null or undefined when calling create2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/accounts/{accountId}/payments`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentCreateRequestToJSON(requestParameters['paymentCreateRequest']),
        };
    }

    /**
     * Создаёт новый платёж для указанного лицевого счёта. Сумма должна быть строго больше нуля. Дата платежа обязательна.
     * Зарегистрировать платёж
     */
    async create2Raw(requestParameters: Create2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponse>> {
        const requestOptions = await this.create2RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseFromJSON(jsonValue));
    }

    /**
     * Создаёт новый платёж для указанного лицевого счёта. Сумма должна быть строго больше нуля. Дата платежа обязательна.
     * Зарегистрировать платёж
     */
    async create2(requestParameters: Create2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponse> {
        const response = await this.create2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAll without sending the request
     */
    async getAllRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/services`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает полный справочник коммунальных услуг. Набор фиксирован: Газ, Вода, Электроэнергия, Домофон, Отопление, Экоресурсы, Жилсервис, Капитальный ремонт. Для каждой услуги указано наличие счётчика и количество цифр в показании.
     * Получить список всех услуг
     */
    async getAllRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceInfoDto>>> {
        const requestOptions = await this.getAllRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceInfoDtoFromJSON));
    }

    /**
     * Возвращает полный справочник коммунальных услуг. Набор фиксирован: Газ, Вода, Электроэнергия, Домофон, Отопление, Экоресурсы, Жилсервис, Капитальный ремонт. Для каждой услуги указано наличие счётчика и количество цифр в показании.
     * Получить список всех услуг
     */
    async getAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceInfoDto>> {
        const response = await this.getAllRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getByAccount without sending the request
     */
    async getByAccountRequestOpts(requestParameters: GetByAccountRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getByAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts/{accountId}/readings`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает все показания счётчика по лицевому счёту, отсортированные по дате (новые первыми).
     * Получить историю показаний
     */
    async getByAccountRaw(requestParameters: GetByAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MeterReadingResponse>>> {
        const requestOptions = await this.getByAccountRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MeterReadingResponseFromJSON));
    }

    /**
     * Возвращает все показания счётчика по лицевому счёту, отсортированные по дате (новые первыми).
     * Получить историю показаний
     */
    async getByAccount(requestParameters: GetByAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MeterReadingResponse>> {
        const response = await this.getByAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getByAccount1 without sending the request
     */
    async getByAccount1RequestOpts(requestParameters: GetByAccount1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getByAccount1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts/{accountId}/payments`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает список всех платежей по лицевому счёту, отсортированных по дате (новые первыми).
     * Получить историю платежей
     */
    async getByAccount1Raw(requestParameters: GetByAccount1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PaymentResponse>>> {
        const requestOptions = await this.getByAccount1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PaymentResponseFromJSON));
    }

    /**
     * Возвращает список всех платежей по лицевому счёту, отсортированных по дате (новые первыми).
     * Получить историю платежей
     */
    async getByAccount1(requestParameters: GetByAccount1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PaymentResponse>> {
        const response = await this.getByAccount1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getById without sending the request
     */
    async getByIdRequestOpts(requestParameters: GetByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает данные лицевого счёта по его уникальному идентификатору.
     * Получить лицевой счёт по ID
     */
    async getByIdRaw(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountResponse>> {
        const requestOptions = await this.getByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountResponseFromJSON(jsonValue));
    }

    /**
     * Возвращает данные лицевого счёта по его уникальному идентификатору.
     * Получить лицевой счёт по ID
     */
    async getById(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountResponse> {
        const response = await this.getByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWithStatus without sending the request
     */
    async getWithStatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/accounts/with-status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Возвращает все лицевые счета с динамически вычисленным статусом оплаты за текущий месяц.  Правила определения статуса: • PAID_THIS_MONTH — есть хотя бы один платёж в текущем месяце • NOT_PAID_THIS_MONTH — платежей нет, текущая дата ≤ 25 • OVERDUE — платежей нет, текущая дата > 25  Выполняется за 2 SQL-запроса (без N+1).
     * Получить все счета со статусом оплаты
     */
    async getWithStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccountWithStatusResponse>>> {
        const requestOptions = await this.getWithStatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountWithStatusResponseFromJSON));
    }

    /**
     * Возвращает все лицевые счета с динамически вычисленным статусом оплаты за текущий месяц.  Правила определения статуса: • PAID_THIS_MONTH — есть хотя бы один платёж в текущем месяце • NOT_PAID_THIS_MONTH — платежей нет, текущая дата ≤ 25 • OVERDUE — платежей нет, текущая дата > 25  Выполняется за 2 SQL-запроса (без N+1).
     * Получить все счета со статусом оплаты
     */
    async getWithStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccountWithStatusResponse>> {
        const response = await this.getWithStatusRaw(initOverrides);
        return await response.value();
    }

}
