/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Запрос на создание лицевого счёта
 * @export
 * @interface AccountCreateRequest
 */
export interface AccountCreateRequest {
    /**
     * Код типа услуги из справочника ServiceType
     * @type {string}
     * @memberof AccountCreateRequest
     */
    serviceType: string;
    /**
     * Номер лицевого счёта. Допустимы цифры, точка, тире. Уникален в рамках услуги
     * @type {string}
     * @memberof AccountCreateRequest
     */
    accountNumber: string;
}

/**
 * Check if a given object implements the AccountCreateRequest interface.
 */
export function instanceOfAccountCreateRequest(value: object): value is AccountCreateRequest {
    if (!('serviceType' in value) || value['serviceType'] === undefined) return false;
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    return true;
}

export function AccountCreateRequestFromJSON(json: any): AccountCreateRequest {
    return AccountCreateRequestFromJSONTyped(json, false);
}

export function AccountCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceType': json['serviceType'],
        'accountNumber': json['accountNumber'],
    };
}

export function AccountCreateRequestToJSON(json: any): AccountCreateRequest {
    return AccountCreateRequestToJSONTyped(json, false);
}

export function AccountCreateRequestToJSONTyped(value?: AccountCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceType': value['serviceType'],
        'accountNumber': value['accountNumber'],
    };
}

