/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Данные лицевого счёта
 * @export
 * @interface AccountResponse
 */
export interface AccountResponse {
    /**
     * Уникальный идентификатор лицевого счёта в системе
     * @type {number}
     * @memberof AccountResponse
     */
    id?: number;
    /**
     * Код типа услуги
     * @type {string}
     * @memberof AccountResponse
     */
    serviceType?: string;
    /**
     * Отображаемое название услуги на русском языке
     * @type {string}
     * @memberof AccountResponse
     */
    serviceDisplayName?: string;
    /**
     * Номер лицевого счёта
     * @type {string}
     * @memberof AccountResponse
     */
    accountNumber?: string;
}

/**
 * Check if a given object implements the AccountResponse interface.
 */
export function instanceOfAccountResponse(value: object): value is AccountResponse {
    return true;
}

export function AccountResponseFromJSON(json: any): AccountResponse {
    return AccountResponseFromJSONTyped(json, false);
}

export function AccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'serviceType': json['serviceType'] == null ? undefined : json['serviceType'],
        'serviceDisplayName': json['serviceDisplayName'] == null ? undefined : json['serviceDisplayName'],
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
    };
}

export function AccountResponseToJSON(json: any): AccountResponse {
    return AccountResponseToJSONTyped(json, false);
}

export function AccountResponseToJSONTyped(value?: AccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'serviceType': value['serviceType'],
        'serviceDisplayName': value['serviceDisplayName'],
        'accountNumber': value['accountNumber'],
    };
}

