/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Лицевой счёт с вычисленным статусом оплаты за текущий месяц
 * @export
 * @interface AccountWithStatusResponse
 */
export interface AccountWithStatusResponse {
    /**
     * Уникальный идентификатор лицевого счёта
     * @type {number}
     * @memberof AccountWithStatusResponse
     */
    accountId?: number;
    /**
     * Код типа услуги
     * @type {string}
     * @memberof AccountWithStatusResponse
     */
    serviceType?: string;
    /**
     * Отображаемое название услуги на русском языке
     * @type {string}
     * @memberof AccountWithStatusResponse
     */
    serviceDisplayName?: string;
    /**
     * Номер лицевого счёта
     * @type {string}
     * @memberof AccountWithStatusResponse
     */
    accountNumber?: string;
    /**
     * Статус оплаты: PAID_THIS_MONTH, NOT_PAID_THIS_MONTH, OVERDUE
     * @type {AccountWithStatusResponseStatusEnum}
     * @memberof AccountWithStatusResponse
     */
    status?: AccountWithStatusResponseStatusEnum;
    /**
     * Отображаемое название статуса на русском языке
     * @type {string}
     * @memberof AccountWithStatusResponse
     */
    statusDisplayName?: string;
}


/**
 * @export
 */
export const AccountWithStatusResponseStatusEnum = {
    PaidThisMonth: 'PAID_THIS_MONTH',
    NotPaidThisMonth: 'NOT_PAID_THIS_MONTH',
    Overdue: 'OVERDUE'
} as const;
export type AccountWithStatusResponseStatusEnum = typeof AccountWithStatusResponseStatusEnum[keyof typeof AccountWithStatusResponseStatusEnum];


/**
 * Check if a given object implements the AccountWithStatusResponse interface.
 */
export function instanceOfAccountWithStatusResponse(value: object): value is AccountWithStatusResponse {
    return true;
}

export function AccountWithStatusResponseFromJSON(json: any): AccountWithStatusResponse {
    return AccountWithStatusResponseFromJSONTyped(json, false);
}

export function AccountWithStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountWithStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'serviceType': json['serviceType'] == null ? undefined : json['serviceType'],
        'serviceDisplayName': json['serviceDisplayName'] == null ? undefined : json['serviceDisplayName'],
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusDisplayName': json['statusDisplayName'] == null ? undefined : json['statusDisplayName'],
    };
}

export function AccountWithStatusResponseToJSON(json: any): AccountWithStatusResponse {
    return AccountWithStatusResponseToJSONTyped(json, false);
}

export function AccountWithStatusResponseToJSONTyped(value?: AccountWithStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'serviceType': value['serviceType'],
        'serviceDisplayName': value['serviceDisplayName'],
        'accountNumber': value['accountNumber'],
        'status': value['status'],
        'statusDisplayName': value['statusDisplayName'],
    };
}

