/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Ответ при ошибке — содержит код, описание и опционально ошибки по полям
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * HTTP-код ответа
     * @type {number}
     * @memberof ErrorResponse
     */
    status?: number;
    /**
     * Тип ошибки
     * @type {string}
     * @memberof ErrorResponse
     */
    error?: string;
    /**
     * Человекочитаемое описание ошибки
     * @type {string}
     * @memberof ErrorResponse
     */
    message?: string;
    /**
     * Ошибки валидации по отдельным полям (только для 400 Validation Failed)
     * @type {{ [key: string]: string; }}
     * @memberof ErrorResponse
     */
    fieldErrors?: { [key: string]: string; };
    /**
     * Время возникновения ошибки
     * @type {Date}
     * @memberof ErrorResponse
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the ErrorResponse interface.
 */
export function instanceOfErrorResponse(value: object): value is ErrorResponse {
    return true;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
    return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
        'fieldErrors': json['fieldErrors'] == null ? undefined : json['fieldErrors'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function ErrorResponseToJSON(json: any): ErrorResponse {
    return ErrorResponseToJSONTyped(json, false);
}

export function ErrorResponseToJSONTyped(value?: ErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': value['error'],
        'message': value['message'],
        'fieldErrors': value['fieldErrors'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
    };
}

