/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Запрос на передачу показания счётчика
 * @export
 * @interface MeterReadingCreateRequest
 */
export interface MeterReadingCreateRequest {
    /**
     * Показание счётчика — строка из цифр фиксированной длины. Газ и Вода: 4 цифры, Электроэнергия: 5 цифр
     * @type {string}
     * @memberof MeterReadingCreateRequest
     */
    value: string;
    /**
     * Дата снятия показания в формате ISO-8601 (YYYY-MM-DD)
     * @type {Date}
     * @memberof MeterReadingCreateRequest
     */
    readingDate: Date;
}

/**
 * Check if a given object implements the MeterReadingCreateRequest interface.
 */
export function instanceOfMeterReadingCreateRequest(value: object): value is MeterReadingCreateRequest {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('readingDate' in value) || value['readingDate'] === undefined) return false;
    return true;
}

export function MeterReadingCreateRequestFromJSON(json: any): MeterReadingCreateRequest {
    return MeterReadingCreateRequestFromJSONTyped(json, false);
}

export function MeterReadingCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeterReadingCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'readingDate': (new Date(json['readingDate'])),
    };
}

export function MeterReadingCreateRequestToJSON(json: any): MeterReadingCreateRequest {
    return MeterReadingCreateRequestToJSONTyped(json, false);
}

export function MeterReadingCreateRequestToJSONTyped(value?: MeterReadingCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'readingDate': value['readingDate'].toISOString().substring(0,10),
    };
}

