/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Данные показания счётчика
 * @export
 * @interface MeterReadingResponse
 */
export interface MeterReadingResponse {
    /**
     * Уникальный идентификатор показания
     * @type {number}
     * @memberof MeterReadingResponse
     */
    id?: number;
    /**
     * Значение показания (строка из цифр)
     * @type {string}
     * @memberof MeterReadingResponse
     */
    value?: string;
    /**
     * Дата снятия показания в формате ISO-8601
     * @type {Date}
     * @memberof MeterReadingResponse
     */
    readingDate?: Date;
}

/**
 * Check if a given object implements the MeterReadingResponse interface.
 */
export function instanceOfMeterReadingResponse(value: object): value is MeterReadingResponse {
    return true;
}

export function MeterReadingResponseFromJSON(json: any): MeterReadingResponse {
    return MeterReadingResponseFromJSONTyped(json, false);
}

export function MeterReadingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeterReadingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'value': json['value'] == null ? undefined : json['value'],
        'readingDate': json['readingDate'] == null ? undefined : (new Date(json['readingDate'])),
    };
}

export function MeterReadingResponseToJSON(json: any): MeterReadingResponse {
    return MeterReadingResponseToJSONTyped(json, false);
}

export function MeterReadingResponseToJSONTyped(value?: MeterReadingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': value['value'],
        'readingDate': value['readingDate'] == null ? value['readingDate'] : value['readingDate'].toISOString().substring(0,10),
    };
}

