/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Данные платежа по лицевому счёту
 * @export
 * @interface PaymentResponse
 */
export interface PaymentResponse {
    /**
     * Уникальный идентификатор платежа
     * @type {number}
     * @memberof PaymentResponse
     */
    id?: number;
    /**
     * Сумма платежа
     * @type {number}
     * @memberof PaymentResponse
     */
    amount?: number;
    /**
     * Дата платежа в формате ISO-8601
     * @type {Date}
     * @memberof PaymentResponse
     */
    paymentDate?: Date;
}

/**
 * Check if a given object implements the PaymentResponse interface.
 */
export function instanceOfPaymentResponse(value: object): value is PaymentResponse {
    return true;
}

export function PaymentResponseFromJSON(json: any): PaymentResponse {
    return PaymentResponseFromJSONTyped(json, false);
}

export function PaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'paymentDate': json['paymentDate'] == null ? undefined : (new Date(json['paymentDate'])),
    };
}

export function PaymentResponseToJSON(json: any): PaymentResponse {
    return PaymentResponseToJSONTyped(json, false);
}

export function PaymentResponseToJSONTyped(value?: PaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'paymentDate': value['paymentDate'] == null ? value['paymentDate'] : value['paymentDate'].toISOString().substring(0,10),
    };
}

