/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Запрос на создание платежа по лицевому счёту
 * @export
 * @interface PaymentCreateRequest
 */
export interface PaymentCreateRequest {
    /**
     * Сумма платежа. Строго больше нуля, два знака после запятой
     * @type {number}
     * @memberof PaymentCreateRequest
     */
    amount: number;
    /**
     * Дата платежа в формате ISO-8601 (YYYY-MM-DD)
     * @type {Date}
     * @memberof PaymentCreateRequest
     */
    paymentDate: Date;
}

/**
 * Check if a given object implements the PaymentCreateRequest interface.
 */
export function instanceOfPaymentCreateRequest(value: object): value is PaymentCreateRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('paymentDate' in value) || value['paymentDate'] === undefined) return false;
    return true;
}

export function PaymentCreateRequestFromJSON(json: any): PaymentCreateRequest {
    return PaymentCreateRequestFromJSONTyped(json, false);
}

export function PaymentCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'paymentDate': (new Date(json['paymentDate'])),
    };
}

export function PaymentCreateRequestToJSON(json: any): PaymentCreateRequest {
    return PaymentCreateRequestToJSONTyped(json, false);
}

export function PaymentCreateRequestToJSONTyped(value?: PaymentCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'paymentDate': value['paymentDate'].toISOString().substring(0,10),
    };
}

