/* tslint:disable */
/* eslint-disable */
/**
 * Utility Payments Tracking System API
 * REST API системы учёта коммунальных платежей.  Система позволяет: - управлять лицевыми счетами по 8 видам коммунальных услуг - регистрировать платежи - передавать показания счётчиков (для услуг с приборами учёта) - отслеживать статус оплаты за текущий месяц 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@utilpay.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Информация о коммунальной услуге из фиксированного справочника
 * @export
 * @interface ServiceInfoDto
 */
export interface ServiceInfoDto {
    /**
     * Код услуги (значение enum ServiceType)
     * @type {string}
     * @memberof ServiceInfoDto
     */
    code?: string;
    /**
     * Отображаемое название услуги на русском языке
     * @type {string}
     * @memberof ServiceInfoDto
     */
    displayName?: string;
    /**
     * Наличие прибора учёта (счётчика) у данной услуги
     * @type {boolean}
     * @memberof ServiceInfoDto
     */
    hasMeter?: boolean;
    /**
     * Количество цифр в показании счётчика. null — если услуга без счётчика
     * @type {number}
     * @memberof ServiceInfoDto
     */
    meterDigits?: number;
}

/**
 * Check if a given object implements the ServiceInfoDto interface.
 */
export function instanceOfServiceInfoDto(value: object): value is ServiceInfoDto {
    return true;
}

export function ServiceInfoDtoFromJSON(json: any): ServiceInfoDto {
    return ServiceInfoDtoFromJSONTyped(json, false);
}

export function ServiceInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'hasMeter': json['hasMeter'] == null ? undefined : json['hasMeter'],
        'meterDigits': json['meterDigits'] == null ? undefined : json['meterDigits'],
    };
}

export function ServiceInfoDtoToJSON(json: any): ServiceInfoDto {
    return ServiceInfoDtoToJSONTyped(json, false);
}

export function ServiceInfoDtoToJSONTyped(value?: ServiceInfoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'displayName': value['displayName'],
        'hasMeter': value['hasMeter'],
        'meterDigits': value['meterDigits'],
    };
}

